#!/bin/sh

if ! hciconfig hci0 > /dev/null 2>&1 ; then
  echo -n "Tring to enable bluetooth... "
  /usr/sbin/rfkill unblock bluetooth
  usleep 1000000
  if ! hciconfig hci0 > /dev/null 2>&1 ; then
    echo "NG"
    exit 1
  fi
  echo "OK"
fi

cd /home/root/thermal-monitor
export NOBLE_REPORT_ALL_HCI_EVENTS=1
exec node main.js
